const gasGlobals = {
  Config: 'writable',
  Classifier: 'writable',
  Labels: 'writable',
  Log: 'writable',
  GmailSearch: 'writable',
  LlmClassifier: 'writable',
  Forwarding: 'writable',
  _ENV: 'writable',
  LABEL_NAMES: 'writable',
  DEFAULT_SUBJECT_KEYWORDS: 'writable',
  DEFAULT_ATTACHMENT_KEYWORDS: 'writable',
  DEFAULT_EXCLUDED_KEYWORDS: 'writable',
  DEFAULT_ATTACHMENT_EXTENSIONS: 'writable',
  DEFAULT_DISCOVERY_DAYS: 'writable',
  DEFAULT_MAX_EMAILS_PER_RUN: 'writable',
  DEFAULT_DRY_RUN: 'writable',
  PropertiesService: 'readonly',
  GmailApp: 'readonly',
  Logger: 'readonly',
  UrlFetchApp: 'readonly',
  Utilities: 'readonly',
  ScriptApp: 'readonly',
  DocumentApp: 'readonly',
  DriveApp: 'readonly',
};

export default [
  {
    ignores: ['node_modules/', 'coverage/', 'src/_env.js'],
  },
  {
    files: ['src/**/*.js'],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: 'script',
      globals: {
        ...gasGlobals,
      },
    },
    rules: {
      'no-unused-vars': ['warn', { args: 'none', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
      'no-constant-condition': 'off',
      'no-empty': 'off',
      'no-redeclare': 'off',
      'no-undef': 'off',
    },
  },
  {
    files: ['test/**/*.js'],
    languageOptions: {
      ecmaVersion: 2020,
      globals: {
        ...gasGlobals,
        jest: 'readonly',
        createMockLabel: 'readonly',
        createMockAttachment: 'readonly',
        createMockMessage: 'readonly',
        createMockThread: 'readonly',
        resetTestState: 'readonly',
        defaultTestProps: 'readonly',
        mockPropsStore: 'writable',
        mockScriptProperties: 'writable',
        mockLabelsRegistry: 'writable',
        mockGmailApp: 'writable',
        mockLoggerLogs: 'writable',
        mockHttpResponse: 'writable',
        mockUrlFetchApp: 'writable',
        mockUtilities: 'writable',
        mockDocBody: 'writable',
        mockDoc: 'writable',
        mockDriveFile: 'writable',
        mockDocumentApp: 'writable',
        mockDriveApp: 'writable',
        mockTriggerList: 'writable',
        mockTriggerBuilder: 'writable',
        mockScriptApp: 'writable',
      },
    },
    rules: {
      'no-unused-vars': 'off',
    },
  },
  {
    files: ['scripts/**/*.js'],
    languageOptions: {
      ecmaVersion: 2020,
      globals: {
        process: 'readonly',
        console: 'readonly',
        require: 'readonly',
        __dirname: 'readonly',
        Buffer: 'readonly',
      },
    },
  },
];
