// AUTO-GENERATED by scripts/generate-transform.js — do not edit manually.
// Regenerate: npm run generate-transform

const knownNames = new Set([
  'Classifier',
  'Config',
  'DEFAULT_ATTACHMENT_EXTENSIONS',
  'DEFAULT_ATTACHMENT_KEYWORDS',
  'DEFAULT_DISCOVERY_DAYS',
  'DEFAULT_DRY_RUN',
  'DEFAULT_EXCLUDED_KEYWORDS',
  'DEFAULT_MAX_EMAILS_PER_RUN',
  'DEFAULT_SUBJECT_KEYWORDS',
  'Forwarding',
  'GmailSearch',
  'LABEL_NAMES',
  'Labels',
  'LlmClassifier',
  'Log'
]);

const knownFunctions = new Set([
  '_shuffle',
  'backfillApprovedSuppliers',
  'backfillSender',
  'bootstrapProperties',
  'clearAllLabels',
  'discoverSuppliers',
  'dryRunBackfill',
  'migrateLabels',
  'processLiveEmails',
  'removeTrigger',
  'setupAll',
  'setupLabels',
  'setupTrigger',
  'smokeTest',
  'status',
  'testSetup',
  'validateConfig'
]);

module.exports = {
  process(src, filename) {
    if (!filename.includes('/src/') || filename.endsWith('.json')) {
      return { code: src, map: null };
    }

    let code = src;

    for (const name of knownNames) {
      const re = new RegExp('^var ' + name + '[ ]*=', 'gm');
      code = code.replace(re, 'global.' + name + ' =');
    }

    for (const name of knownFunctions) {
      const re = new RegExp('^function ' + name + '\\(', 'gm');
      code = code.replace(re, 'global.' + name + ' = function(');
    }

    return { code, map: null };
  },
};
