const fs = require('fs');
const path = require('path');

const SRC_DIR = path.resolve(__dirname, '../../src');
const EXPORTED_RE = /\/\*\s*exported\s+([^*]+)\s*\*\//g;
const VAR_RE = /^var\s+([A-Za-z_$][\w$]*)\s*=/;

function scanSrcFiles() {
  return fs.readdirSync(SRC_DIR)
    .filter(f => f.endsWith('.js') && f !== '_env.js')
    .map(f => ({
      name: f,
      content: fs.readFileSync(path.join(SRC_DIR, f), 'utf8'),
    }));
}

function extractExported(content) {
  const names = [];
  let match;
  while ((match = EXPORTED_RE.exec(content)) !== null) {
    match[1].split(',').forEach(n => names.push(n.trim()));
  }
  return names;
}

function extractVarNames(content) {
  const names = [];
  content.split('\n').forEach(line => {
    const m = line.match(VAR_RE);
    if (m) names.push(m[1]);
  });
  return names;
}

function build() {
  const files = scanSrcFiles();
  const exportedFunctions = new Set();
  const exportedVars = new Set();

  for (const file of files) {
    const exported = extractExported(file.content);
    const varNames = extractVarNames(file.content);

    for (const name of exported) {
      if (varNames.includes(name)) {
        exportedVars.add(name);
      } else {
        exportedFunctions.add(name);
      }
    }
  }

  return { exportedVars, exportedFunctions };
}

const { exportedVars, exportedFunctions } = build();

const varEntries = [...exportedVars].sort().map(v => '  \'' + v + '\'').join(',\n');
const fnEntries = [...exportedFunctions].sort().map(v => '  \'' + v + '\'').join(',\n');

const output = `// AUTO-GENERATED by scripts/generate-transform.js — do not edit manually.
// Regenerate: npm run generate-transform

const knownNames = new Set([
${varEntries}
]);

const knownFunctions = new Set([
${fnEntries}
]);

module.exports = {
  process(src, filename) {
    if (!filename.includes('/src/') || filename.endsWith('.json')) {
      return { code: src, map: null };
    }

    let code = src;

    for (const name of knownNames) {
      const re = new RegExp('^var ' + name + '[ ]*=', 'gm');
      code = code.replace(re, 'global.' + name + ' =');
    }

    for (const name of knownFunctions) {
      const re = new RegExp('^function ' + name + '\\\\(', 'gm');
      code = code.replace(re, 'global.' + name + ' = function(');
    }

    return { code, map: null };
  },
};
`;

const outPath = path.resolve(__dirname, 'gas-modules.js');
fs.writeFileSync(outPath, output, 'utf8');
console.log('Generated test/transform/gas-modules.js');
console.log('  Vars:      ' + [...exportedVars].sort().join(', '));
console.log('  Functions: ' + [...exportedFunctions].sort().join(', '));
