#!/usr/bin/env node
// scripts/build-env.js
// Reads .env and writes src/_env.js — a global object that Apps Script can use
// to bootstrap Script Properties via bootstrapProperties() in setup.js.
//
// Run: npm run build-env
// Then: clasp push

const path = require('path');
const fs   = require('fs');
require('dotenv').config({ path: path.resolve(__dirname, '../.env') });

const KEYS = [
  'FORWARD_TO_EMAIL',
  'ALLOWED_SENDERS',
  'ALLOWED_DOMAINS',
  'EXCLUDED_SENDERS',
  'EXCLUDED_DOMAINS',
  'DISCOVERY_DAYS',
  'BACKFILL_AFTER_DATE',
  'DRY_RUN',
  'MAX_EMAILS_PER_RUN',
  'ENABLE_LIVE_FORWARDING',
  'CANDIDATE_LABEL',
  'FORWARDED_LABEL',
  'REJECTED_LABEL',
  'DISCOVERED_LABEL',
];

const props = {};
for (const key of KEYS) {
  const val = process.env[key];
  if (val !== undefined && val !== '') {
    props[key] = val;
  }
}

const lines = Object.entries(props).map(
  ([k, v]) => `  ${k}: ${JSON.stringify(v)},`
);

const output = `// AUTO-GENERATED by scripts/build-env.js — do not edit manually.
// Gitignored. Pushed to Apps Script via clasp push.
// Run: npm run build-env && clasp push
// Then run bootstrapProperties() once in the Apps Script editor.
var _ENV = {
${lines.join('\n')}
};
`;

const outPath = path.resolve(__dirname, '../src/_env.js');
fs.writeFileSync(outPath, output, 'utf8');
console.log('Wrote src/_env.js with', Object.keys(props).length, 'properties.');
console.log('Next: clasp push  →  run bootstrapProperties() in Apps Script editor');
