#!/usr/bin/env node
// scripts/build-env.js
// Reads .env and writes src/_env.js — a global object that Apps Script can use
// to bootstrap Script Properties via bootstrapProperties() in setup.js.
//
// Run: npm run build-env
// Then: clasp push

const path = require('path');
const fs   = require('fs');
require('dotenv').config({ path: path.resolve(__dirname, '../.env') });

const KEYS = [
  'FORWARD_TO_EMAIL',
  'ALLOWED_SENDERS',
  'ALLOWED_DOMAINS',
  'EXCLUDED_SENDERS',
  'EXCLUDED_DOMAINS',
  'DISCOVERY_DAYS',
  'BACKFILL_AFTER_DATE',
  'DRY_RUN',
  'MAX_EMAILS_PER_RUN',
  'ENABLE_LIVE_FORWARDING',
  'CANDIDATE_LABEL',
  'FORWARDED_LABEL',
  'REJECTED_LABEL',
  'DISCOVERED_LABEL',
  'ENABLE_LLM_CLASSIFICATION',
  'LLM_API_KEY',
  'LLM_BASE_URL',
  'LLM_MODEL',
  'LLM_CONFIDENCE_THRESHOLD',
];

const props = {};
for (const key of KEYS) {
  const val = process.env[key];
  if (val !== undefined && val !== '') {
    props[key] = val;
  }
}

// Auto-derive BACKFILL_AFTER_DATE from DISCOVERY_DAYS if not explicitly set.
if (!props['BACKFILL_AFTER_DATE']) {
  const days = parseInt(props['DISCOVERY_DAYS'] || '365', 10);
  const d = new Date();
  d.setDate(d.getDate() - days);
  const yyyy = d.getFullYear();
  const mm   = String(d.getMonth() + 1).padStart(2, '0');
  const dd   = String(d.getDate()).padStart(2, '0');
  props['BACKFILL_AFTER_DATE'] = `${yyyy}/${mm}/${dd}`;
  console.log(`Auto-computed BACKFILL_AFTER_DATE=${props['BACKFILL_AFTER_DATE']} (${days} days ago)`);
}

const lines = Object.entries(props).map(
  ([k, v]) => `  ${k}: ${JSON.stringify(v)},`
);

const output = `// AUTO-GENERATED by scripts/build-env.js — do not edit manually.
// Gitignored. Pushed to Apps Script via clasp push.
// Run: npm run build-env && clasp push
// Then run bootstrapProperties() once in the Apps Script editor.
var _ENV = {
${lines.join('\n')}
};
`;

const outPath = path.resolve(__dirname, '../src/_env.js');
fs.writeFileSync(outPath, output, 'utf8');
console.log('Wrote src/_env.js with', Object.keys(props).length, 'properties.');
console.log('Next: clasp push  →  run bootstrapProperties() in Apps Script editor');
