// setup.js
// Bootstrap utilities: label setup, trigger creation, config validation.

// Step 1 after first push: sets Script Properties from _ENV (generated by build-env.js),
// creates labels, and validates config. Run once in the Apps Script editor.
function bootstrapProperties() {
  if (typeof _ENV === 'undefined') {
    throw new Error('_ENV is not defined. Run `npm run build-env && clasp push` first.');
  }
  // Filter out empty-string values so we don't overwrite existing properties with blanks
  var toSet = {};
  Object.keys(_ENV).forEach(function (k) {
    if (_ENV[k] !== '') toSet[k] = _ENV[k];
  });
  PropertiesService.getScriptProperties().setProperties(toSet);
  Logger.log('Script Properties set: ' + JSON.stringify(Object.keys(toSet)));
  setupLabels();
  validateConfig();
  Logger.log('Bootstrap complete. Run discoverSuppliers() next.');
}

// Run this once after first deployment to create labels and install the trigger.
function setupAll() {
  validateConfig();
  setupLabels();
  Logger.log('Setup complete. Run discoverSuppliers() next.');
}

function setupLabels() {
  Labels.setup();
}

// Install a time-driven trigger for processLiveEmails() every 15 minutes.
// Safe to call multiple times — will not create duplicates.
function setupTrigger() {
  var triggers = ScriptApp.getProjectTriggers();
  for (var i = 0; i < triggers.length; i++) {
    if (triggers[i].getHandlerFunction() === 'processLiveEmails') {
      Logger.log('Trigger already exists for processLiveEmails. Skipping.');
      return;
    }
  }
  ScriptApp.newTrigger('processLiveEmails')
    .timeBased()
    .everyMinutes(15)
    .create();
  Logger.log('Time-driven trigger created: processLiveEmails every 15 minutes.');
}

// Remove all triggers for processLiveEmails (kill switch).
function removeTrigger() {
  var triggers = ScriptApp.getProjectTriggers();
  var removed = 0;
  for (var i = 0; i < triggers.length; i++) {
    if (triggers[i].getHandlerFunction() === 'processLiveEmails') {
      ScriptApp.deleteTrigger(triggers[i]);
      removed++;
    }
  }
  Logger.log('Removed ' + removed + ' trigger(s) for processLiveEmails.');
}

function validateConfig() {
  var errors = [];

  try {
    Config.getForwardToEmail();
  } catch (e) {
    errors.push('FORWARD_TO_EMAIL is not set.');
  }

  var senders = Config.getAllowedSenders();
  var domains = Config.getAllowedDomains();
  if (senders.length === 0 && domains.length === 0) {
    errors.push('No ALLOWED_SENDERS or ALLOWED_DOMAINS set. Discovery will work but backfill/live will forward nothing.');
  }

  if (errors.length > 0) {
    Logger.log('CONFIG WARNINGS:\n' + errors.join('\n'));
  } else {
    Logger.log('Config looks good.');
  }

  Logger.log('Current config: ' + JSON.stringify(Config.dump(), null, 2));
}

// Migrate threads from old label names to the current configured label names.
// Safe to run multiple times — skips threads already carrying the new label.
// After migration, manually delete the old labels in Gmail Settings > Labels.
function migrateLabels() {
  var MIGRATIONS = [
    { from: 'revolut-forwarded',  to: Config.getForwardedLabel()  },
    { from: 'revolut-rejected',   to: Config.getRejectedLabel()   },
    { from: 'revolut-candidate',  to: Config.getCandidateLabel()  },
    { from: 'revolut-discovered', to: Config.getDiscoveredLabel() },
  ];

  MIGRATIONS.forEach(function (m) {
    var oldLabel = GmailApp.getUserLabelByName(m.from);
    if (!oldLabel) {
      Logger.log('Skipping "' + m.from + '" — label does not exist.');
      return;
    }

    // Ensure the new label exists
    var newLabel = GmailApp.getUserLabelByName(m.to);
    if (!newLabel) newLabel = GmailApp.createLabel(m.to);

    var threads = oldLabel.getThreads();
    Logger.log('Migrating "' + m.from + '" → "' + m.to + '" (' + threads.length + ' threads)');

    threads.forEach(function (thread) {
      thread.addLabel(newLabel);
      thread.removeLabel(oldLabel);
    });

    Logger.log('Done. You can now delete the "' + m.from + '" label in Gmail Settings > Labels.');
  });

  Logger.log('Migration complete.');
}

// Remove all gmail-smart-forward/* labels from every thread that carries them.
// Use this to reset state before a fresh backfill (e.g. after changing the allowlist).
// Does NOT delete the label objects themselves — only strips them from threads.
function clearAllLabels() {
  var labels = [
    { name: Config.getForwardedLabel(),  label: Labels.getForwarded()  },
    { name: Config.getRejectedLabel(),   label: Labels.getRejected()   },
    { name: Config.getCandidateLabel(),  label: Labels.getCandidate()  },
    { name: Config.getDiscoveredLabel(), label: Labels.getDiscovered() },
  ];

  labels.forEach(function (entry) {
    var threads = entry.label.getThreads();
    Logger.log('Clearing "' + entry.name + '" from ' + threads.length + ' threads...');
    threads.forEach(function (thread) {
      thread.removeLabel(entry.label);
    });
    Logger.log('Done.');
  });

  Logger.log('All labels cleared. You can now run a fresh backfill.');
}

// Quick smoke test — does not send any email.
function testSetup() {
  validateConfig();
  setupLabels();
  Logger.log('testSetup: OK');
}
