/* exported bootstrapProperties, setupAll, setupLabels, setupTrigger, removeTrigger, validateConfig, status, migrateLabels, clearAllLabels, testSetup */
// setup.js
// Bootstrap utilities: label setup, trigger creation, config validation.

// Step 1 after first push: sets Script Properties from _ENV (generated by build-env.js),
// creates labels, and validates config. Run once in the Apps Script editor.
function bootstrapProperties() {
  if (typeof _ENV === 'undefined') {
    throw new Error('_ENV is not defined. Run `npm run build-env && clasp push` first.');
  }
  // Filter out empty-string values so we don't overwrite existing properties with blanks
  var toSet = {};
  Object.keys(_ENV).forEach(function (k) {
    if (_ENV[k] !== '' && _ENV[k].trim() !== '') toSet[k] = _ENV[k].trim();
  });
  PropertiesService.getScriptProperties().setProperties(toSet);
  Logger.log('Script Properties set: ' + JSON.stringify(Object.keys(toSet)));
  setupLabels();
  validateConfig();
  Logger.log('Bootstrap complete. Run discoverSuppliers() next.');
}

// Run this once after first deployment to create labels and install the trigger.
function setupAll() {
  validateConfig();
  setupLabels();
  Logger.log('Setup complete. Run discoverSuppliers() next.');
}

function setupLabels() {
  Labels.setup();
}

// Install a time-driven trigger for processLiveEmails() every 15 minutes.
// Safe to call multiple times — will not create duplicates.
function setupTrigger() {
  var triggers = ScriptApp.getProjectTriggers();
  if (!triggers) {
    Logger.log('ScriptApp.getProjectTriggers() returned null. Skipping trigger setup.');
    return;
  }
  for (var i = 0; i < triggers.length; i++) {
    if (triggers[i].getHandlerFunction() === 'processLiveEmails') {
      Logger.log('Trigger already exists for processLiveEmails. Skipping.');
      return;
    }
  }
  ScriptApp.newTrigger('processLiveEmails')
    .timeBased()
    .everyMinutes(15)
    .create();
  Logger.log('Time-driven trigger created: processLiveEmails every 15 minutes.');
}

// Remove all triggers for processLiveEmails (kill switch).
function removeTrigger() {
  var triggers = ScriptApp.getProjectTriggers();
  if (!triggers) {
    Logger.log('No triggers found (getProjectTriggers returned null).');
    return;
  }
  var removed = 0;
  for (var i = 0; i < triggers.length; i++) {
    if (triggers[i].getHandlerFunction() === 'processLiveEmails') {
      ScriptApp.deleteTrigger(triggers[i]);
      removed++;
    }
  }
  Logger.log('Removed ' + removed + ' trigger(s) for processLiveEmails.');
}

function validateConfig() {
  var errors = [];
  var warnings = [];

  var email = null;
  try {
    email = Config.getForwardToEmail();
    if (email && !/@/.test(email)) {
      errors.push('FORWARD_TO_EMAIL "' + email + '" does not look like a valid email address.');
    }
  } catch (_e) {
    errors.push('FORWARD_TO_EMAIL is not set. This is required for forwarding to work.');
  }

  var senders = Config.getAllowedSenders();
  var domains = Config.getAllowedDomains();
  if (senders.length === 0 && domains.length === 0) {
    warnings.push('No ALLOWED_SENDERS or ALLOWED_DOMAINS set. Discovery will work but backfill/live will forward nothing.');
  }

  var excludedSenders = Config.getExcludedSenders();
  var excludedDomains = Config.getExcludedDomains();
  excludedSenders.forEach(function (s) {
    if (senders.indexOf(s) !== -1) {
      errors.push('"' + s + '" is in both ALLOWED_SENDERS and EXCLUDED_SENDERS.');
    }
  });
  excludedDomains.forEach(function (d) {
    if (domains.indexOf(d) !== -1) {
      errors.push('"' + d + '" is in both ALLOWED_DOMAINS and EXCLUDED_DOMAINS.');
    }
  });

  var extensions = Config.getAttachmentExtensions();
  var rawExtensions = PropertiesService.getScriptProperties().getProperty('ATTACHMENT_EXTENSIONS');
  if (rawExtensions !== null && rawExtensions.trim() === '') {
    errors.push('ATTACHMENT_EXTENSIONS is set but empty. No attachments will match — nothing will be forwarded.');
  } else {
    extensions.forEach(function (ext) {
      if (ext.indexOf('.') !== -1) {
        warnings.push('ATTACHMENT_EXTENSIONS contains "' + ext + '" with a dot prefix. Use plain extensions (e.g. "pdf" not ".pdf").');
      }
    });
  }

  var live = Config.isLiveForwardingEnabled();
  if (live && senders.length === 0 && domains.length === 0) {
    errors.push('ENABLE_LIVE_FORWARDING is true but no allowlist is configured. Nothing will be forwarded.');
  }

  if (Config.isLlmEnabled()) {
    var apiKey = Config.getLlmApiKey();
    if (!apiKey) {
      errors.push('ENABLE_LLM_CLASSIFICATION is true but LLM_API_KEY is not set.');
    }
    var threshold = Config.getLlmConfidenceThreshold();
    if (threshold < 0 || threshold > 1) {
      errors.push('LLM_CONFIDENCE_THRESHOLD must be between 0 and 1, got ' + threshold + '.');
    }
    // Warn if the raw value was garbage and silently replaced with default
    var rawThreshold = PropertiesService.getScriptProperties().getProperties()['LLM_CONFIDENCE_THRESHOLD'];
    if (rawThreshold !== undefined && rawThreshold.trim() !== '' && isNaN(parseFloat(rawThreshold))) {
      warnings.push('LLM_CONFIDENCE_THRESHOLD value "' + rawThreshold + '" is not a number — using default 0.7.');
    }
  }

  var result = { errors: errors, warnings: warnings };

  if (errors.length > 0) {
    Logger.log('CONFIG ERRORS:\n' + errors.join('\n'));
  }
  if (warnings.length > 0) {
    Logger.log('CONFIG WARNINGS:\n' + warnings.join('\n'));
  }
  if (errors.length === 0 && warnings.length === 0) {
    Logger.log('Config looks good.');
  }

  Logger.log('Current config: ' + JSON.stringify(Config.dump(), null, 2));
  return result;
}

function status() {
  var dryRun = Config.isDryRun();
  var live = Config.isLiveForwardingEnabled();
  var state;
  if (dryRun && !live) {
    state = 'Preview (DRY_RUN=true, ENABLE_LIVE_FORWARDING=false)';
  } else if (!dryRun && !live) {
    state = 'Backfill (DRY_RUN=false, ENABLE_LIVE_FORWARDING=false)';
  } else if (!dryRun && live) {
    state = 'Live (DRY_RUN=false, ENABLE_LIVE_FORWARDING=true)';
  } else {
    state = 'Invalid (DRY_RUN=true, ENABLE_LIVE_FORWARDING=true) — live forwarding is enabled but dry-run is also on.';
  }

  var triggers = ScriptApp.getProjectTriggers();
  var hasTrigger = false;
  if (triggers) {
    for (var i = 0; i < triggers.length; i++) {
      if (triggers[i].getHandlerFunction() === 'processLiveEmails') {
        hasTrigger = true;
        break;
      }
    }
  }

  var labelCounts = {};
  var labelNames = [
    { key: 'Candidate', getter: Labels.getCandidate },
    { key: 'Forwarded', getter: Labels.getForwarded },
    { key: 'Rejected',  getter: Labels.getRejected },
    { key: 'Discovered', getter: Labels.getDiscovered },
  ];
  labelNames.forEach(function (entry) {
    var label = entry.getter();
    labelCounts[entry.key] = label ? label.getThreads().length : 0;
  });

  Logger.log('=== STATUS ===');
  Logger.log('State: ' + state);
  Logger.log('Trigger: ' + (hasTrigger ? 'Active (processLiveEmails every 15 min)' : 'Not installed'));
  Logger.log('Forward to: ' + (function () { try { return Config.getForwardToEmail(); } catch (_e) { return '(not set)'; } })());
  Logger.log('Allowed senders: ' + (Config.getAllowedSenders().join(', ') || '(none)'));
  Logger.log('Allowed domains: ' + (Config.getAllowedDomains().join(', ') || '(none)'));
  Logger.log('LLM classification: ' + (Config.isLlmEnabled() ? 'Enabled (' + Config.getLlmModel() + ')' : 'Disabled'));
  Logger.log('Labels:');
  Logger.log('  Candidate:  ' + labelCounts.Candidate + ' threads');
  Logger.log('  Forwarded:  ' + labelCounts.Forwarded + ' threads');
  Logger.log('  Rejected:   ' + labelCounts.Rejected + ' threads');
  Logger.log('  Discovered: ' + labelCounts.Discovered + ' threads');

  var validation = validateConfig();
  if (validation.errors.length === 0 && validation.warnings.length === 0) {
    Logger.log('Config validation: OK');
  } else {
    Logger.log('Config validation: ' + validation.errors.length + ' error(s), ' + validation.warnings.length + ' warning(s)');
  }
}

// Migrate threads from old label names to the current configured label names.
// Safe to run multiple times — skips threads already carrying the new label.
// After migration, manually delete the old labels in Gmail Settings > Labels.
function migrateLabels() {
  var MIGRATIONS = [
    { from: 'revolut-forwarded',  to: Config.getForwardedLabel()  },
    { from: 'revolut-rejected',   to: Config.getRejectedLabel()   },
    { from: 'revolut-candidate',  to: Config.getCandidateLabel()  },
    { from: 'revolut-discovered', to: Config.getDiscoveredLabel() },
  ];

  MIGRATIONS.forEach(function (m) {
    var oldLabel = GmailApp.getUserLabelByName(m.from);
    if (!oldLabel) {
      Logger.log('Skipping "' + m.from + '" — label does not exist.');
      return;
    }

    // Ensure the new label exists
    var newLabel = GmailApp.getUserLabelByName(m.to);
    if (!newLabel) newLabel = GmailApp.createLabel(m.to);

    var threads = oldLabel.getThreads();
    Logger.log('Migrating "' + m.from + '" → "' + m.to + '" (' + threads.length + ' threads)');

    threads.forEach(function (thread) {
      thread.addLabel(newLabel);
      thread.removeLabel(oldLabel);
    });

    Logger.log('Done. You can now delete the "' + m.from + '" label in Gmail Settings > Labels.');
  });

  Logger.log('Migration complete.');
}

// Remove all gmail-smart-forward/* labels from every thread that carries them.
// Use this to reset state before a fresh backfill (e.g. after changing the allowlist).
// Does NOT delete the label objects themselves — only strips them from threads.
function clearAllLabels() {
  var labels = [
    { name: Config.getForwardedLabel(),  label: Labels.getForwarded()  },
    { name: Config.getRejectedLabel(),   label: Labels.getRejected()   },
    { name: Config.getCandidateLabel(),  label: Labels.getCandidate()  },
    { name: Config.getDiscoveredLabel(), label: Labels.getDiscovered() },
  ];

  labels.forEach(function (entry) {
    var threads = entry.label.getThreads();
    if (!threads) {
      Logger.log('Clearing "' + entry.name + '": no threads (getThreads returned null).');
      return;
    }
    Logger.log('Clearing "' + entry.name + '" from ' + threads.length + ' threads...');
    threads.forEach(function (thread) {
      thread.removeLabel(entry.label);
    });
    Logger.log('Done.');
  });

  Logger.log('All labels cleared. You can now run a fresh backfill.');
}

// Quick smoke test — does not send any email.
function testSetup() {
  validateConfig();
  setupLabels();
  Logger.log('testSetup: OK');
}
